[project]
name = "agenttracks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.4.301",
    "fastapi[all]>=0.115.12",
    "openai-agents>=0.0.6",
    "pydantic-ai>=0.0.43",
]
