# -*- coding: utf-8 -*-
# pylint: disable=E0213
"""
复杂任务路线图的数据结构
"""

from datetime import datetime
from typing import List, Literal, Tuple, Optional, Any, Dict
from pydantic import BaseModel, Field, field_validator


def get_current_time_message() -> str:
    """
    返回当前时间作为格式化字符串。

    返回：
        str: 格式化为 'YYYY-MM-DD HH:MM:SS' 的当前时间。
    """
    return f"Current time is {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"


WORKER_PROGRESS_SUMMARY = (
    "## Instruction\n"
    "Review the execution trace above and generate a comprehensive summary "
    "report in Markdown format that addresses the original task/query. "
    "Your report must include:\n\n"
    "1. **Task Overview**\n"
    "   - Include the original query/task verbatim;\n"
    "   - Briefly state the main objective.\n"
    "2. **Comprehensive Analysis**"
    "   - Provide a detailed, structured answer to the original query/task;\n"
    "   - Include all relevant information requested in the original task;\n"
    "   - Support your findings with specific references from your execution "
    "trace;\n"
    "   - Organize content into logical sections with appropriate headings;\n"
    "   - Include data visualizations, tables, or formatted lists when "
    "applicable.\n\n"
    "3. **Completion Checklist**\n"
    "   - Reproduce the original 'Expected Output' checklist of required "
    "tasks/information; **NEVER** makeup additional expected output items "
    "in the checklist\n"
    "   - Mark each item as [x] Completed or [ ] Incomplete;\n"
    "   - For each completed item, reference where in your report this "
    "information appears;\n"
    "   - For incomplete items, explain briefly why they remain unaddressed;\n"
    "4. **Conclusion**\n"
    "   - If the task is fully complete, provide a brief conclusion "
    "summarizing key findings;\n"
    "   - If the task remains incomplete, outline a specific plan to "
    "address remaining items, including:\n"
    "     - Which tools would be used;\n"
    "     - What information is still needed;\n"
    "     - Sequence of planned actions.\n\n"
    "Format your report professionally with consistent heading levels, "
    "proper spacing, and appropriate emphasis for key information."
)


WORKER_NEXT_STEP_INSTRUCTION = """
If the subtask remains incomplete, outline a specific plan to address remaining
items, including:
     - Which tools would be used
     - What information is still needed
     - Sequence of planned actions
Leave it as an empty string is the subtask has been done successfully.
"""

WORKER_FILE_COLLECTION_INSTRUCTION = (
    "Collect all files generated in the execution process, "
    "such as the files generated by `write_file` and `edit_file`."
    "This field MUST be in dictionary, where"
    "the keys are the paths of generated files "
    "(e.g. '/FULL/PATH/OF/FILE_1.md') and the values are short "
    "descriptions about the generated files."
)


class WorkerResponse(BaseModel):
    """
    表示工作器 agent 任务执行后的响应结构。

    此类定义工作器响应的预期格式，包括
    进度摘要、下一步、工具使用信息和任务完成状态。

    属性：
        subtask_progress_summary (str):
            任务执行的综合摘要报告。
        next_step (str):
            如果任务未完成，则计划的下一步操作的描述。
        generated_files (dict):
            将文件路径映射到生成文件描述的字典。
        task_done (bool):
            指示任务是否已完成的标志。
    """

    subtask_progress_summary: str = Field(
        ...,
        description=WORKER_PROGRESS_SUMMARY,
    )
    next_step: str = Field(
        ...,
        description=WORKER_NEXT_STEP_INSTRUCTION,
    )
    generated_files: dict = Field(
        ...,
        description=WORKER_FILE_COLLECTION_INSTRUCTION,
    )
    task_done: bool = Field(
        ...,
        description="Whether task is done or it require addition effort",
    )


class Update(BaseModel):
    """表示任务执行期间来自工作器的更新记录。

    此类跟踪工作器在处理子任务时的进度更新，
    包括状态更改、进度摘要和执行详细信息。

    属性：
        reason_for_status (str): 当前状态的解释。
        task_done (bool): 任务是否已完成。
        subtask_progress_summary (str): 已取得进展的摘要。
        next_step (str): 计划的下一步操作的描述。
        worker (str): 提供更新的工作器的标识符。
        attempt_idx (int): 当前尝试的索引。
    """

    reason_for_status: str
    task_done: bool
    subtask_progress_summary: str
    next_step: str
    worker: str
    attempt_idx: int

    @field_validator(
        "subtask_progress_summary",
        "reason_for_status",
        "next_step",
        "worker",
        mode="before",
    )
    def _stringify(cls, v: Any) -> str:
        """确保属性是字符串"""
        if v is None:
            return ""
        return str(v)


class WorkerInfo(BaseModel):
    """包含分配给子任务的工作器 agent 的信息。

    此类存储有关工作器 agent 的元数据，包括它们的
    能力、创建类型和配置详细信息。

    属性：
        worker_name (str):
            工作器的名称标识符。
        status (str):
            工作器的当前状态。
        create_type (Literal["built-in", "dynamic-built"]):
            工作器的创建方式。
        description (str):
            工作器用途和能力的描述。
        tool_lists (List[str]):
            此工作器可用的工具列表。
        sys_prompt (str):
            用于配置工作器的系统提示。
    """

    worker_name: str = ""
    status: str = ""
    create_type: Literal["built-in", "dynamic-built"] = "dynamic-built"
    description: str = ""
    # 用于动态创建工作器 agent
    tool_lists: List[str] = Field(default_factory=list)
    sys_prompt: str = ""

    @field_validator(
        "worker_name",
        "status",
        mode="before",
    )
    def _stringify(cls, v: Any) -> str:
        """字符串化验证器"""
        if v is None:
            return ""
        return str(v)


class SubTaskSpecification(BaseModel):
    """
    较大任务分解中的子任务详细信息。
    """

    subtask_description: str = Field(description="子任务的描述。")
    input_intro: str = Field(
        ...,
        description="子任务输入的介绍或上下文。",
    )
    exact_input: str = Field(
        ...,
        description="子任务的确切输入数据或参数。",
    )
    expected_output: str = Field(
        ...,
        description="子任务的预期输出数据或参数。",
    )
    desired_auxiliary_tools: str = Field(
        ...,
        description="对此子任务有帮助的工具。",
    )

    @field_validator(
        "subtask_description",
        "input_intro",
        "exact_input",
        "expected_output",
        "desired_auxiliary_tools",
        mode="before",
    )
    def _stringify(cls, v: Any) -> str:
        """字符串化验证器"""
        if v is None:
            return ""
        return str(v)


class SubTaskStatus(BaseModel):
    """
    表示较大任务分解中子任务的状态和详细信息。

    此类跟踪各个子任务、它们的执行状态、
    分配的工作器以及整个执行生命周期中的进度更新。

    属性：
        status (Literal["Planned", "In-process", "Done"]):
            当前执行状态。
        updates (List[Update]):
            来自工作器的进度更新列表。
        attempt (int):
            此子任务的执行尝试次数。
        workers (List[WorkerInfo]):
            分配给此子任务的工作器列表。
    """

    subtask_specification: SubTaskSpecification = Field(
        default_factory=SubTaskSpecification,
    )
    status: Literal["Planned", "In-process", "Done"] = "Planned"
    updates: List[Update] = Field(
        default_factory=list,
        description=("来自工作器的更新列表。初始化时必须是空列表。"),
    )
    attempt: int = 0
    workers: List[WorkerInfo] = Field(
        default_factory=list,
        description=("已分配给此子任务的工作器列表。初始化子任务时必须为空。"),
    )


class RoadMap(BaseModel):
    """表示任务分解和执行跟踪的路线图。

    此类管理整体任务分解，包含原始任务描述
    以及具有执行状态的已分解子任务列表。

    属性：
        original_task (str):
            分解前的原始任务描述。
        decomposed_tasks (List[SubTaskStatus]):
            从原始任务创建的子任务列表。
    """

    original_task: str = ""
    decomposed_tasks: List[SubTaskStatus] = Field(default_factory=list)

    def next_unfinished_subtask(
        self,
    ) -> Tuple[Optional[int], Optional[SubTaskStatus]]:
        """查找下一个尚未完成的子任务。

        遍历已分解的任务以查找状态为 "Planned" 或 "In-process" 的第一个子任务。

        返回：
            Tuple[Optional[int], Optional[SubTaskStatus]]: 包含以下内容的元组：
                - 下一个未完成子任务的索引（如果所有任务都已完成，则为 None）
                - 下一个未完成子任务的 SubTaskStatus 对象
                  （如果所有任务都已完成，则为 None）
        """
        for i, subtask in enumerate(self.decomposed_tasks):
            if subtask.status in ["Planned", "In-process"]:
                return i, subtask
        return None, None


class PlannerNoteBook(BaseModel):
    """
    表示规划器笔记本。

    属性：
        time (str): 当前时间消息。
        user_input (List[str]): 用户输入列表。
        detail_analysis_for_plan (str): 计划的详细分析。
        roadmap (RoadMap): 与规划器关联的路线图。
        files (Dict[str, str]): 与规划器相关的文件字典。
        full_tool_list (dict[str, dict]): 工具的完整模式。
    """

    time: str = Field(default_factory=get_current_time_message)
    user_input: List[str] = Field(default_factory=list)
    detail_analysis_for_plan: str = (
        "Unknown. Please call `build_roadmap_and_decompose_task` to analyze."
    )
    roadmap: RoadMap = Field(default_factory=RoadMap)
    files: Dict[str, str] = Field(default_factory=dict)
    full_tool_list: list[dict] = Field(default_factory=list)
